version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - "18080:18080"
      - "15000:15000/udp"
    environment:
      - MODE=true